// <auto-generated />
namespace QuickTableProyect.Persistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class PorSiLasMoscas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PorSiLasMoscas));
        
        string IMigrationMetadata.Id
        {
            get { return "202510270056290_PorSiLasMoscas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
